version: '3'
services:
  web:
    build: .
    volumes:
      - .:/app
      - ./instance:/app/instance  
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py 
      - FLASK_ENV=development
